### ISSUE TITLE
wrapper不可用的吧？

### ISSUE THREAD

**Issue by cfanbo** [callmez/yii2-file-system#6]
// wrapper 方式 (推荐)
  //等同于Yii::$app->fileSystem->get('local')->write('test.txt', 'hello world');
  Yii::$app->fileSystem->write('local://test.txt', 'hello world'); 
  //等同于Yii::$app->fileSystem->get('qiniu')->write('test.txt', 'hello world');
  Yii::$app->fileSystem->write('qiniu://test.txt', 'hello world'); 
# 

上传到七牛成这个样子了
$qiniu->write('qiniu://aa.txt' , 'hello world wrapper');

结果：
qiniu:/aa.txt

**Comment by cfanbo** [comment]
难道用法错了？

**Comment by callmez** [comment]
结果什么?

**Comment by pgyf** [comment]
支持阿里云的oss吗

**Comment by callmez** [comment]
@liyunfang 不支持..但是有计划支持
